import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { GlobalContextProvider } from "../context/MainContext";

const mont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={mont.className}>
      <GlobalContextProvider>
          {children}
      </GlobalContextProvider>
          </body>
    </html>
  );
}
